import { expect, test } from '@playwright/test'

const backend = process.env.AISPACE_E2E_BACKEND_URL || 'http://127.0.0.1:8000'
const github = process.env.AISPACE_GITHUB_MOCK_URL
test.skip(!github, 'Run with scripts/e2e_github.py and its isolated GitHub fixture')

test.beforeEach(async ({ request }) => {
  await request.post(`${github}/fixture`, { data: {} })
  await request.patch(`${backend}/api/github/connection`, { data: { token: null } })
  await request.patch(`${backend}/api/settings`, { data: { execution_mode: 'api', api_key: 'local-test-key', model: 'planner-fixture', base_url: `${process.env.AISPACE_E2E_PROVIDER_URL}/v1` } })
})

test('all GitHub pages, search, persistent selection and complete snapshot reach the planner', async ({ page, request }, testInfo) => {
  const before = await (await request.get(`${backend}/api/workspaces`)).json()
  await page.goto('/')
  await page.getByRole('button', { name: 'Свернуть боковую панель', exact: true }).click()
  await page.getByRole('button', { name: 'Импортировать GitHub Issues', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Импортировать GitHub Issues', exact: true })
  await dialog.getByRole('textbox', { name: 'Репозиторий GitHub', exact: true }).fill('https://github.com/demo/project')
  await dialog.getByRole('button', { name: 'Загрузить issues', exact: true }).click()
  await expect(dialog.getByText('Public · Загружено issues: 22', { exact: true })).toBeVisible()
  await expect(dialog.getByRole('checkbox', { name: 'Выбрать issue #13', exact: true })).toHaveCount(0)
  await dialog.getByRole('checkbox', { name: 'Выбрать issue #1', exact: true }).check()
  await dialog.getByRole('button', { name: 'Следующая страница', exact: true }).click()
  await dialog.getByRole('checkbox', { name: 'Выбрать issue #22', exact: true }).check()
  await expect(dialog.getByRole('heading', { name: 'Выбрано issues: 2', exact: true })).toBeVisible()
  await dialog.getByRole('textbox', { name: 'Поиск по номеру или заголовку', exact: true }).fill('Вторая страница')
  await expect(dialog.getByRole('checkbox', { name: 'Выбрать issue #22', exact: true })).toBeChecked()
  await dialog.getByRole('textbox', { name: 'Поиск по номеру или заголовку', exact: true }).fill('')
  await dialog.getByRole('combobox', { name: 'Состояние issues', exact: true }).selectOption('closed')
  await dialog.getByText('Описание #23 (Markdown)', { exact: true }).click()
  await expect(dialog.getByText('Описание отсутствует.', { exact: true })).toBeVisible()
  await dialog.getByRole('checkbox', { name: 'Выбрать issue #23', exact: true }).check()
  await expect(dialog.getByRole('heading', { name: 'Выбрано issues: 3', exact: true })).toBeVisible()
  const prepared = page.waitForResponse(response => response.url().endsWith('/api/github/selections') && response.request().method() === 'POST')
  await dialog.getByRole('button', { name: 'Построить граф', exact: true }).click()
  const snapshot = await (await prepared).json()
  await expect(page.getByRole('heading', { name: 'Граф из GitHub Issues', exact: true })).toBeVisible()
  expect(snapshot.issues.map((item: { number: number }) => item.number)).toEqual([1, 22, 23])
  expect(snapshot.issues[1].body).toContain('## Полное описание #22')
  expect(snapshot.issues[1].dependencies.blocked_by).toHaveLength(2)
  expect(snapshot.issues[2].body).toBe('')
  expect(await (await request.get(`${backend}/api/github/selections/${snapshot.id}`)).json()).toEqual(snapshot)
  expect(await (await request.get(`${backend}/api/workspaces`)).json()).toEqual(before)
  const audit = await (await request.get(`${github}/audit`)).json()
  expect(audit.requests.every((entry: { method: string; authenticated: boolean }) => entry.method === 'GET' && !entry.authenticated)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('github-selection-ready.png'), fullPage: true })
})

test('repository switch requires reset, failed access preserves selection, same numbers have different IDs', async ({ page, request }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Импортировать GitHub Issues', exact: true }).click()
  const dialog = page.getByRole('dialog')
  const input = dialog.getByRole('textbox', { name: 'Репозиторий GitHub', exact: true })
  await input.fill('demo/project')
  await dialog.getByRole('button', { name: 'Загрузить issues', exact: true }).click()
  await dialog.getByRole('checkbox', { name: 'Выбрать issue #1', exact: true }).check()
  page.once('dialog', popup => popup.dismiss())
  await input.fill('demo/other')
  await dialog.getByRole('button', { name: 'Загрузить issues', exact: true }).click()
  await expect(dialog.getByRole('heading', { name: 'Выбрано issues: 1', exact: true })).toBeVisible()
  page.once('dialog', popup => popup.accept())
  await input.fill('demo/private')
  await dialog.getByRole('button', { name: 'Загрузить issues', exact: true }).click()
  await expect(dialog.getByRole('alert')).toContainText('либо недоступны')
  await expect(dialog.getByRole('heading', { name: 'Выбрано issues: 1', exact: true })).toBeVisible()
  page.once('dialog', popup => popup.accept())
  await input.fill('demo/other')
  await dialog.getByRole('button', { name: 'Загрузить issues', exact: true }).click()
  await expect(dialog.getByRole('heading', { name: 'Выбрано issues: 0', exact: true })).toBeVisible()
  await dialog.getByRole('checkbox', { name: 'Выбрать issue #1', exact: true }).check()
  const prepared = page.waitForResponse(response => response.url().endsWith('/api/github/selections'))
  await dialog.getByRole('button', { name: 'Построить граф', exact: true }).click()
  const snapshot = await (await prepared).json()
  expect(snapshot.repository.id).toBe(200)
  expect(snapshot.issues[0].id).toBe(200001)
  expect(snapshot.issues[0].url).toBe('https://github.com/demo/other/issues/1')
  expect((await (await request.get(`${github}/audit`)).json()).requests.every((item: { method: string }) => item.method === 'GET')).toBe(true)
})

test('separate GitHub token enables private access without leaking into storage or responses', async ({ page, request }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Настройки', exact: true }).click()
  await page.getByRole('textbox', { name: 'Токен GitHub', exact: true }).fill('github-e2e-token')
  await page.getByRole('button', { name: 'Сохранить токен GitHub', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Токен GitHub', exact: true })).toHaveValue('')
  expect(await page.evaluate(() => JSON.stringify({ ...sessionStorage, ...localStorage }))).not.toContain('github-e2e-token')
  expect(await (await request.get(`${backend}/api/github/connection`)).json()).toEqual({ token_configured: true })
  expect(await (await request.get(`${backend}/api/settings`)).text()).not.toContain('github-e2e-token')
  await page.getByRole('button', { name: 'Импортировать GitHub Issues', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByRole('textbox', { name: 'Репозиторий GitHub', exact: true }).fill('demo/private')
  await dialog.getByRole('button', { name: 'Загрузить issues', exact: true }).click()
  await expect(dialog.getByText('Private · Загружено issues: 22', { exact: true })).toBeVisible()
  expect(await page.content()).not.toContain('github-e2e-token')
  expect((await (await request.get(`${github}/audit`)).json()).requests.every((item: { authenticated: boolean }) => item.authenticated)).toBe(true)
})

test('empty mobile app import handles rate limits and failed dependency reads explicitly', async ({ page, request }) => {
  for (const workspace of await (await request.get(`${backend}/api/workspaces`)).json()) await request.delete(`${backend}/api/workspaces/${workspace.id}`)
  await request.post(`${github}/fixture`, { data: { rate_remaining: 1 } })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await page.getByRole('button', { name: 'Свернуть боковую панель', exact: true }).click()
  await page.getByRole('button', { name: 'Импортировать GitHub Issues', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByRole('textbox', { name: 'Репозиторий GitHub', exact: true }).fill('demo/project')
  await dialog.getByRole('button', { name: 'Загрузить issues', exact: true }).click()
  await expect(dialog.getByRole('alert')).toContainText('Лимит GitHub')
  await expect.poll(async () => {
    const response = await request.post(`${backend}/api/github/repository`, { data: { repository: 'demo/project' } })
    return response.status()
  }, { intervals: [1000] }).toBe(200)
  await dialog.getByRole('button', { name: 'Загрузить issues', exact: true }).click()
  await dialog.getByRole('checkbox', { name: 'Выбрать issue #1', exact: true }).check()
  await request.post(`${github}/fixture`, { data: { missing_issue: 1 } })
  await dialog.getByRole('button', { name: 'Построить граф', exact: true }).click()
  await expect(dialog.getByRole('alert')).toContainText('либо недоступны')
  await expect(dialog.getByRole('heading', { name: 'Выбрано issues: 1', exact: true })).toBeVisible()
  await request.post(`${github}/fixture`, { data: { dependencies_failure: true } })
  await dialog.getByRole('button', { name: 'Построить граф', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Граф из GitHub Issues', exact: true })).toBeVisible()
  await expect(page.getByRole('alert')).toContainText('Не прочитаны зависимости')
  expect(await (await request.get(`${backend}/api/workspaces`)).json()).toEqual([])
})
