import { expect, test, type APIRequestContext, type Page } from '@playwright/test'

const backend = `${(process.env.AISPACE_E2E_API_URL || 'http://127.0.0.1:8000').replace(/\/$/, '')}/api`
const provider = 'http://127.0.0.1:8766'
const providerBaseUrl = process.env.AISPACE_E2E_PROVIDER_URL || `${provider}/v1`
const selector = (page: Page) => page.getByRole('combobox', { name: 'Рабочее пространство', exact: true })
const node = (page: Page, id: string) => page.locator(`.react-flow__node[data-id="${id}"]`)
const scope = (id: string) => `${backend}/workspaces/${id}`

async function createWorkspace(request: APIRequestContext, name: string) {
  const response = await request.post(`${backend}/workspaces`, { data: { name } })
  expect(response.ok()).toBeTruthy()
  return response.json()
}

async function createTasklet(request: APIRequestContext, wid: string, title: string, delay = 0.1) {
  const response = await request.post(`${scope(wid)}/tasklets`, { data: { title, prompt: `[[label:${title}]][[delay:${delay}]]`, position: { x: 100, y: 100 } } })
  expect(response.ok()).toBeTruthy()
  return response.json()
}

async function snapshot(request: APIRequestContext, wid: string) {
  const response = await request.get(scope(wid))
  expect(response.ok()).toBeTruthy()
  return response.json()
}

test.beforeEach(async ({ request }) => {
  for (const item of await (await request.get(`${backend}/workspaces`)).json()) {
    expect((await request.post(`${scope(item.id)}/pipeline/stop`)).ok()).toBeTruthy()
    expect((await request.delete(scope(item.id))).ok()).toBeTruthy()
  }
  expect((await request.patch(`${backend}/settings`, { data: { execution_mode: 'api', api_key: 'local-test-key', base_url: providerBaseUrl, model: 'test-model', max_parallel: 2 } })).ok()).toBeTruthy()
  await request.post(`${provider}/reset`)
})

test('create, rename and delete the last workspace without recreating it on refresh', async ({ page, request }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Создать пространство', exact: true }).first().click()
  let dialog = page.getByRole('dialog', { name: 'Создать пространство', exact: true })
  await dialog.getByRole('textbox', { name: 'Название пространства', exact: true }).fill('Проект A')
  await dialog.getByRole('button', { name: 'Создать пространство', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  const wid = await selector(page).inputValue()
  expect(wid).toBeTruthy()
  expect(await snapshot(request, wid)).toMatchObject({ name: 'Проект A', tasklets: [], edges: [], workspace_context: '', working_directory: null })
  await page.getByRole('button', { name: 'Переименовать пространство', exact: true }).click()
  dialog = page.getByRole('dialog', { name: 'Переименовать пространство', exact: true })
  await dialog.getByRole('textbox', { name: 'Название пространства', exact: true }).fill('Новое название')
  await dialog.getByRole('button', { name: 'Переименовать пространство', exact: true }).click()
  await expect.poll(async () => (await snapshot(request, wid)).name).toBe('Новое название')
  await page.reload()
  await expect(selector(page)).toHaveValue(wid)
  await page.getByRole('button', { name: 'Удалить пространство', exact: true }).click()
  dialog = page.getByRole('dialog', { name: 'Удалить пространство', exact: true })
  await expect(dialog).toContainText('Новое название')
  await dialog.getByRole('button', { name: 'Удалить пространство', exact: true }).click()
  await expect.poll(async () => (await (await request.get(`${backend}/workspaces`)).json()).length).toBe(0)
  await page.reload()
  await expect(page.getByRole('button', { name: 'Создать пространство', exact: true }).first()).toBeVisible()
  expect(await (await request.get(`${backend}/workspaces`)).json()).toEqual([])
  expect((await (await request.get(`${backend}/settings`)).json()).api_key_configured).toBe(true)
})

test('each workspace restores its own draft, selection and viewport across switching and reload', async ({ page, request }, testInfo) => {
  const a = await createWorkspace(request, 'Проект A')
  const b = await createWorkspace(request, 'Проект B')
  const ta = await createTasklet(request, a.id, 'Карточка A')
  const tb = await createTasklet(request, b.id, 'Карточка B')
  await page.goto('/')
  await selector(page).selectOption(a.id)
  await node(page, ta.id).click()
  await page.getByRole('tab', { name: /^Чат/ }).click()
  await page.getByPlaceholder('Напишите сообщение…', { exact: true }).fill('Черновик A')
  await page.getByRole('button', { name: 'Уменьшить масштаб', exact: true }).click()
  const viewportA = await page.locator('.react-flow__viewport').getAttribute('style')
  await page.getByRole('button', { name: 'Настройки', exact: true }).click()
  await page.getByRole('button', { name: /^Пространство/ }).click()
  await expect(page.locator('.react-flow__viewport')).toHaveAttribute('style', viewportA!)
  await selector(page).selectOption(b.id)
  await expect(node(page, ta.id)).toHaveCount(0)
  await node(page, tb.id).click()
  await page.getByRole('tab', { name: /^Чат/ }).click()
  await expect(page.getByPlaceholder('Напишите сообщение…', { exact: true })).toHaveValue('')
  await page.getByPlaceholder('Напишите сообщение…', { exact: true }).fill('Черновик B')
  await selector(page).selectOption(a.id)
  await expect(page.getByPlaceholder('Напишите сообщение…', { exact: true })).toHaveValue('Черновик A')
  await expect(page.locator('.react-flow__viewport')).toHaveAttribute('style', viewportA!)
  await page.reload()
  await expect(selector(page)).toHaveValue(a.id)
  await expect(page.getByPlaceholder('Напишите сообщение…', { exact: true })).toHaveValue('Черновик A')
  await expect(page.locator('.react-flow__viewport')).toHaveAttribute('style', viewportA!)
  await selector(page).selectOption(b.id)
  await expect(page.getByPlaceholder('Напишите сообщение…', { exact: true })).toHaveValue('Черновик B')
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('button', { name: 'Скрыть боковую панель', exact: true }).click()
  await expect(selector(page)).toBeVisible()
  await selector(page).selectOption(a.id)
  await expect(page.getByPlaceholder('Напишите сообщение…', { exact: true })).toHaveValue('Черновик A')
  await page.screenshot({ path: testInfo.outputPath('mobile-workspace-switch.png'), fullPage: true })
  expect(await (await request.get(`${scope(a.id)}/tasklets/${ta.id}/messages`)).json()).toEqual([])
  expect(await (await request.get(`${scope(b.id)}/tasklets/${tb.id}/messages`)).json()).toEqual([])
  expect(await page.evaluate(() => sessionStorage.getItem('aispace.ui.v1'))).not.toContain('local-test-key')
})

test('tabs select workspaces independently and recover when their workspace is deleted elsewhere', async ({ page, context, request }) => {
  const a = await createWorkspace(request, 'Первая вкладка')
  const b = await createWorkspace(request, 'Вторая вкладка')
  await page.goto('/')
  await selector(page).selectOption(a.id)
  const second = await context.newPage()
  await second.goto('/')
  await selector(second).selectOption(b.id)
  await expect(selector(page)).toHaveValue(a.id)
  await page.reload()
  await second.reload()
  await expect(selector(page)).toHaveValue(a.id)
  await expect(selector(second)).toHaveValue(b.id)
  expect((await request.delete(scope(b.id))).ok()).toBeTruthy()
  await expect(selector(second)).toHaveValue(a.id)
  await second.reload()
  await expect(selector(second)).toHaveValue(a.id)
})

test('unsaved tasklet, settings and creation forms survive refresh without sending changes', async ({ page, request }) => {
  const a = await createWorkspace(request, 'Черновики A')
  const b = await createWorkspace(request, 'Черновики B')
  const tasklet = await createTasklet(request, a.id, 'Сохранённый тасклет')
  await page.goto('/')
  await selector(page).selectOption(a.id)
  await node(page, tasklet.id).click()
  await page.getByRole('textbox', { name: 'Промпт', exact: true }).fill('Несохранённая инструкция A')
  await selector(page).selectOption(b.id)
  await selector(page).selectOption(a.id)
  await expect(page.getByRole('textbox', { name: 'Промпт', exact: true })).toHaveValue('Несохранённая инструкция A')
  await page.reload()
  await expect(page.getByRole('textbox', { name: 'Промпт', exact: true })).toHaveValue('Несохранённая инструкция A')
  expect((await snapshot(request, a.id)).tasklets[0].prompt).toBe(tasklet.prompt)
  await page.getByRole('button', { name: 'Настройки', exact: true }).click()
  await page.getByRole('textbox', { name: 'Контекст пространства', exact: true }).fill('Несохранённый контекст A')
  await page.getByLabel('API-ключ', { exact: true }).fill('unsaved-private-key')
  await selector(page).selectOption(b.id)
  await page.getByRole('button', { name: 'Настройки', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Контекст пространства', exact: true })).toHaveValue('')
  await selector(page).selectOption(a.id)
  await page.reload()
  await expect(page.getByRole('textbox', { name: 'Контекст пространства', exact: true })).toHaveValue('Несохранённый контекст A')
  await expect(page.getByLabel('API-ключ', { exact: true })).toHaveValue('')
  expect((await snapshot(request, a.id)).workspace_context).toBe('')
  expect(await page.evaluate(() => sessionStorage.getItem('aispace.ui.v1'))).not.toContain('unsaved-private-key')
  await page.getByRole('button', { name: /^Пространство/ }).click()
  await page.getByRole('button', { name: 'Новый тасклет', exact: true }).click()
  let dialog = page.getByRole('dialog')
  await dialog.getByRole('textbox', { name: 'Название', exact: true }).fill('Черновик нового тасклета')
  await dialog.getByRole('textbox', { name: 'Промпт', exact: true }).fill('Ничего не отправлять')
  await page.reload()
  dialog = page.getByRole('dialog')
  await expect(dialog.getByRole('textbox', { name: 'Название', exact: true })).toHaveValue('Черновик нового тасклета')
  await expect(dialog.getByRole('textbox', { name: 'Промпт', exact: true })).toHaveValue('Ничего не отправлять')
  expect((await snapshot(request, a.id)).tasklets).toHaveLength(1)
  expect((await snapshot(request, a.id)).pipeline.status).toBe('idle')
})

test('Codex keeps separate workspace contexts, directories and threads when chats are resumed', async ({ page, request }) => {
  const a = await createWorkspace(request, 'Codex A')
  const b = await createWorkspace(request, 'Codex B')
  const root = (await (await request.get(`${backend}/directories`)).json()).path.replace(/\/$/, '')
  expect((await request.patch(`${backend}/settings`, { data: { execution_mode: 'codex', model: '', api_key: null } })).ok()).toBeTruthy()
  for (const [item, folder, context] of [[a, 'demo', 'Контекст проекта A'], [b, 'other', 'Контекст проекта B']] as const) {
    expect((await request.patch(scope(item.id), { data: { working_directory: `${root}/${folder}`, workspace_context: context } })).ok()).toBeTruthy()
  }
  const ta = await createTasklet(request, a.id, 'codex-space-a')
  const tb = await createTasklet(request, b.id, 'codex-space-b')
  expect((await request.post(`${scope(a.id)}/pipeline/start`)).ok()).toBeTruthy()
  await expect.poll(async () => (await snapshot(request, a.id)).pipeline.status).toBe('completed')
  const completedA = await snapshot(request, a.id)
  expect((await request.post(`${scope(b.id)}/pipeline/start`)).ok()).toBeTruthy()
  await expect.poll(async () => (await snapshot(request, b.id)).pipeline.status).toBe('completed')
  expect(await snapshot(request, a.id)).toEqual(completedA)
  await page.goto('/')
  await selector(page).selectOption(a.id)
  await node(page, ta.id).click()
  await page.getByRole('tab', { name: /^Чат/ }).click()
  await page.getByPlaceholder('Напишите сообщение…', { exact: true }).fill('Продолжи [[label:codex-space-a-resume]]')
  await page.getByRole('button', { name: 'Отправить сообщение', exact: true }).click()
  await expect(page.getByText('Готово: codex-space-a-resume.', { exact: true })).toBeVisible()
  const events = (await (await request.get(`${provider}/audit`)).json()).events.filter((event: { transport: string; kind: string }) => event.transport === 'codex' && event.kind === 'start')
  expect(events.map((event: { label: string }) => event.label)).toEqual(['codex-space-a', 'codex-space-b', 'codex-space-a-resume'])
  expect(events[0].thread_id).not.toBe(events[1].thread_id)
  expect(events[2].thread_id).toBe(events[0].thread_id)
  expect(events[0].parameters.cwd).toBe(`${root}/demo`)
  expect(events[1].parameters.cwd).toBe(`${root}/other`)
  expect(JSON.stringify(events[0])).toContain('Контекст проекта A')
  expect(JSON.stringify(events[0])).not.toContain('Контекст проекта B')
  expect(JSON.stringify(events[1])).toContain('Контекст проекта B')
  expect(JSON.stringify(events[1])).not.toContain('Контекст проекта A')
  expect((await (await request.get(`${scope(a.id)}/tasklets/${ta.id}/messages`)).json()).length).toBe(4)
  expect((await (await request.get(`${scope(b.id)}/tasklets/${tb.id}/messages`)).json()).length).toBe(2)
})

test('a delayed save preserves a newer draft entered after switching away and back', async ({ page, request }) => {
  const a = await createWorkspace(request, 'Сохранение A')
  const b = await createWorkspace(request, 'Сохранение B')
  const tasklet = await createTasklet(request, a.id, 'Редактирование')
  await page.goto('/')
  await selector(page).selectOption(a.id)
  await node(page, tasklet.id).click()
  let release: () => void = () => {}
  const gate = new Promise<void>(resolve => { release = resolve })
  let intercepted = false
  let delivered = false
  await page.route(`**/api/workspaces/${a.id}/tasklets/${tasklet.id}`, async route => {
    const response = await route.fetch()
    intercepted = true
    await gate
    await route.fulfill({ response })
    delivered = true
  })
  await page.getByRole('textbox', { name: 'Промпт', exact: true }).fill('Отправленная инструкция')
  await page.getByRole('button', { name: 'Сохранить изменения', exact: true }).click()
  await expect.poll(() => intercepted).toBe(true)
  await selector(page).selectOption(b.id)
  await selector(page).selectOption(a.id)
  await page.getByRole('textbox', { name: 'Промпт', exact: true }).fill('Более новый черновик')
  release()
  await expect.poll(() => delivered).toBe(true)
  await expect(page.getByRole('textbox', { name: 'Промпт', exact: true })).toHaveValue('Более новый черновик')
  await page.reload()
  await expect(page.getByRole('textbox', { name: 'Промпт', exact: true })).toHaveValue('Более новый черновик')
  expect((await snapshot(request, a.id)).tasklets[0].prompt).toBe('Отправленная инструкция')
})

test('a late workspace settings response preserves tasks and drafts created by a newer event', async ({ page, request }) => {
  const a = await createWorkspace(request, 'Поздние настройки')
  const b = await createWorkspace(request, 'Другое пространство')
  await page.goto('/')
  await selector(page).selectOption(a.id)
  await page.getByRole('button', { name: 'Настройки', exact: true }).click()
  let release: () => void = () => {}
  const gate = new Promise<void>(resolve => { release = resolve })
  let intercepted = false
  let delivered = false
  await page.route(`**/api/workspaces/${a.id}`, async route => {
    if (route.request().method() !== 'PATCH') return route.continue()
    const response = await route.fetch()
    intercepted = true
    await gate
    await route.fulfill({ response })
    delivered = true
  })
  await page.getByRole('textbox', { name: 'Контекст пространства', exact: true }).fill('Сохранённый контекст')
  await page.getByRole('button', { name: 'Сохранить пространство', exact: true }).click()
  await expect.poll(() => intercepted).toBe(true)
  await selector(page).selectOption(b.id)
  const newTasklet = await createTasklet(request, a.id, 'Новая карточка из другой вкладки')
  await selector(page).selectOption(a.id)
  await page.getByRole('button', { name: /^Пространство/ }).click()
  await node(page, newTasklet.id).click()
  await page.getByRole('textbox', { name: 'Промпт', exact: true }).fill('Свежий черновик')
  release()
  await expect.poll(() => delivered).toBe(true)
  await expect(page.getByText('Настройки пространства сохранены', { exact: true })).toBeVisible()
  await expect(node(page, newTasklet.id)).toBeVisible()
  await expect(page.getByRole('textbox', { name: 'Промпт', exact: true })).toHaveValue('Свежий черновик')
  await page.reload()
  await expect(node(page, newTasklet.id)).toBeVisible()
  await expect(page.getByRole('textbox', { name: 'Промпт', exact: true })).toHaveValue('Свежий черновик')
  expect((await snapshot(request, a.id)).workspace_context).toBe('Сохранённый контекст')
})

test('running workspace stays active while another is edited and deleted', async ({ page, request }, testInfo) => {
  const a = await createWorkspace(request, 'Выполняющийся проект с подробным названием для проверки переключения между пространствами')
  const b = await createWorkspace(request, 'Другой проект')
  await createTasklet(request, a.id, 'Долгая задача', 20)
  const taskletB = await createTasklet(request, b.id, 'Другая задача')
  await page.goto('/')
  await selector(page).selectOption(a.id)
  await page.getByRole('button', { name: 'Запустить пайплайн', exact: true }).click()
  await expect.poll(async () => (await snapshot(request, a.id)).pipeline.status).toBe('running')
  await expect(page.getByRole('button', { name: 'Удалить пространство', exact: true })).toBeDisabled()
  await selector(page).selectOption(b.id)
  await expect(page.getByRole('button', { name: 'Открыть выполняющееся пространство', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Запустить пайплайн', exact: true })).toBeDisabled()
  await node(page, taskletB.id).click()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('button', { name: 'Открыть выполняющееся пространство', exact: true }).click({ trial: true })
  await expect(selector(page)).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('mobile-other-workspace-running.png'), fullPage: true })
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.getByRole('button', { name: 'Настройки', exact: true }).click()
  await page.getByRole('textbox', { name: 'Контекст пространства', exact: true }).fill('Контекст B')
  await page.getByRole('button', { name: 'Сохранить пространство', exact: true }).click()
  await expect.poll(async () => (await snapshot(request, b.id)).workspace_context).toBe('Контекст B')
  await expect(page.getByRole('textbox', { name: 'Модель по умолчанию', exact: true })).toBeDisabled()
  await page.reload()
  await expect(selector(page)).toHaveValue(b.id)
  expect((await snapshot(request, a.id)).pipeline.status).toBe('running')
  await page.screenshot({ path: testInfo.outputPath('other-workspace-running.png'), fullPage: true })
  expect((await request.post(`${scope(b.id)}/pipeline/start`)).status()).toBe(409)
  expect((await request.post(`${scope(b.id)}/pipeline/stop`)).ok()).toBeTruthy()
  expect((await snapshot(request, a.id)).pipeline.status).toBe('running')
  expect((await request.delete(scope(a.id))).status()).toBe(409)
  expect((await request.delete(scope(b.id))).ok()).toBeTruthy()
  await expect(selector(page)).toHaveValue(a.id)
  expect((await snapshot(request, a.id)).pipeline.status).toBe('running')
  expect((await request.post(`${scope(a.id)}/pipeline/stop`)).ok()).toBeTruthy()
  await expect.poll(async () => (await snapshot(request, a.id)).pipeline.status).toBe('cancelled')
})

test('late workspace and chat responses cannot replace the newly selected workspace', async ({ page, request }) => {
  const a = await createWorkspace(request, 'Медленное A')
  const b = await createWorkspace(request, 'Быстрое B')
  const ta = await createTasklet(request, a.id, 'Только A')
  const tb = await createTasklet(request, b.id, 'Только B')
  expect((await request.post(`${scope(a.id)}/pipeline/start`)).ok()).toBeTruthy()
  await expect.poll(async () => (await snapshot(request, a.id)).pipeline.status).toBe('completed')
  await page.goto('/')
  await selector(page).selectOption(a.id)
  await node(page, ta.id).click()
  await selector(page).selectOption(b.id)
  let releaseWorkspace: () => void = () => {}
  const workspaceGate = new Promise<void>(resolve => { releaseWorkspace = resolve })
  let workspaceIntercepted = false
  let workspaceDelivered = false
  await page.route(`**/api/workspaces/${a.id}`, async route => {
    const response = await route.fetch()
    workspaceIntercepted = true
    await workspaceGate
    await route.fulfill({ response })
    workspaceDelivered = true
  })
  await selector(page).selectOption(a.id)
  await expect.poll(() => workspaceIntercepted).toBe(true)
  await selector(page).selectOption(b.id)
  releaseWorkspace()
  await expect.poll(() => workspaceDelivered).toBe(true)
  await expect(selector(page)).toHaveValue(b.id)
  await expect(node(page, tb.id)).toBeVisible()
  await expect(node(page, ta.id)).toHaveCount(0)
  await page.unroute(`**/api/workspaces/${a.id}`)
  let release: () => void = () => {}
  const gate = new Promise<void>(resolve => { release = resolve })
  let intercepted = 0
  let delivered = false
  await page.route(`**/api/workspaces/${a.id}/tasklets/${ta.id}/messages`, async route => {
    const response = await route.fetch()
    intercepted++
    await gate
    await route.fulfill({ response })
    delivered = true
  })
  await selector(page).selectOption(b.id)
  await selector(page).selectOption(a.id)
  await expect.poll(() => intercepted).toBeGreaterThan(0)
  await selector(page).selectOption(b.id)
  await node(page, tb.id).click()
  await page.getByRole('tab', { name: /^Чат/ }).click()
  release()
  await expect.poll(() => delivered).toBe(true)
  await expect(node(page, ta.id)).toHaveCount(0)
  await expect(page.getByText('Готово: Только A.', { exact: false })).toHaveCount(0)
  await page.unroute(`**/api/workspaces/${a.id}/tasklets/${ta.id}/messages`)
  expect((await request.post(`${scope(a.id)}/pipeline/start`)).ok()).toBeTruthy()
  await expect.poll(async () => (await snapshot(request, a.id)).pipeline.status).toBe('completed')
  await expect(node(page, tb.id)).toBeVisible()
  await expect(node(page, ta.id)).toHaveCount(0)
  await expect(selector(page)).toHaveValue(b.id)
  await selector(page).selectOption(a.id)
  await page.getByRole('tab', { name: /^Чат/ }).click()
  const count = (await (await request.get(`${scope(a.id)}/tasklets/${ta.id}/messages`)).json()).length
  await expect(page.locator('.chat-message')).toHaveCount(count)
})
